version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:8
    steps:
      - checkout

      - run:
          name: Set up Java 8 and Maven 3.9
          command: |
            java -version
            mvn -version

      - run:
          name: Build and Test
          command: |
            cd src/main/java/com/myapp
            mvn clean install -U -Dmaven.test.skip=true -X

      - run:
          name: Deploy to SonarQube
          command: |
            cd src/main/java/com/myapp
            mvn sonar:sonar -Dsonar.host.url=http://localhost:9000 -Dsonar.login=80be99ab5dd15155e5ef57f2dce3b161d736c069 -X

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
